- numerox_example.py
Here's a numerox example. See #10. It should not be used until numerox 2.5.0 is released. Just wanted to see if there is any interest in adding it.
> add numerox example

- numerox_example.py
> update numerox example for numerox 3.0.0

- example_model.py
- example_model.r
also remove mention of consistency
> change logloss to auc

- example_model.py
Replace old LogisticRegression with a newer sklearn model that performs better.
Previous output:
```
- probabilities: [0.51572388 0.46585226 0.50565621 0.47901625 0.48293951]
- target: 1    1.0
2    0.0
3    0.0
4    0.0
5    1.0
Name: target_bernie, dtype: float64
- rounded probability: [1.0, 0.0, 1.0, 0.0, 0.0]
- accuracy:  0.5118750445759932
- bernie vs elizabeth corr: [[1.         0.77605042]
[0.77605042 1.        ]]
- elizabeth using bernie: 0.5106269167677056
- validation AUC: 0.5161824242999602
- joined:                  id  probability
0  n00183d2eed2c463     0.495533
1  n00187fa497c9d5b     0.515724
2  n001acd04f3617b7     0.465852
3  n0043a13252683ee     0.505656
4  n00535e274720abd     0.479016
```
New output:
```
- probabilities: [0.51482354 0.47924622 0.52007783 0.49808894 …
```
> Add new python model

- example_model.r
- replace all mentions of corscore with correlation
- update benchmark from 0 to 0.002 to be consistent with python example
```
> #Tutorial and Tips for Numerai
> 
> #***
> #The stock market is the hardest data science problem in the world.
> #If it seems easy, you're doing it wrong.
> #We don't know how to solve this problem. But here is what we know.
> #We need your help. You take it from here.
> #***
> library(Metrics)
> library(gbm)
Loaded gbm 2.1.4
> library(randomForest)
randomForest 4.6-14
Type rfNews() to see new features/changes/bug fixes.
> 
> print("THIS SCRIPT DOWNSAMPLES DATA AND WILL LIKELY UNDERPERFORM THE example_predictions.csv")
[1] "THIS SCRIPT DOWNSAMPLES DATA AND WILL LIKELY UNDERPERFORM THE example_predictions.csv"
> 
> #the training data is used to train your model …
```
> fix correlation in r script

- Introduction to Numerai.html
- Introduction to Numerai.ipynb
added introduction guide for new users to NMR
> Add Introduction to Numerai.ipynb

- analysis_and_tips.ipynb
http://jupyter.numer.ai:8080/notebooks/notebooks/Michael/analysis_and_tips.ipynb#
Add code to neutralize predictions to feature columns, and show how it can improve sharpe.
> added feature neutralization code and example

- Cross_Validation_and_Model_Optimization.ipynb
This notebook provides working code to partition training data into train and test sets, cross validation, and grid search.
> Notebook used to teach Financial Machine Learning - Part II

- example_model.py
- fix score function to reflect new payout rules
- tidy up various comments
- change the example model to be the REAL example predictions model and leave a comment about how to make it faster
- add tips on how to optimize for memory
> fix example script to reflect payout rules

- example_model.py
A couple of minor changes to the XGBoost example model script.
1. Save the XGBoost model after training. Subsequent runs will use this saved model if present, for inference instead of training the model from scratch.
2. `id` is the first column in both train and tournament csv files. Specifying the index_col when the file is being loaded is a bit faster than loading the file without specifying an index column (which creates a `RangeIndex` by default) and then reindexing the DataFrame with the `id` column.
3. Split a string literal that was triggering flake8’s [E501](https://www.flake8rules.com/rules/E501.html) line too long warning (Set to >= 120 chars on my machine).
> Load and save the trained example model

- example_model.py
Includes all code needed to replicate the diagnostics metrics shown on submission
> add code for validation diagnostics

- example_model.r
Per MikeP's request in rocket-chat — I updated the R example file. Removed all strings including "kazutsugi" and successfully tested a manual upload of new csv submission to Numerai website.
> Updated R example to remove kazutsugi strings

- signals/example_model.py
If there is no date in `full_data` for `date_string`, copy the structure of `full_data` for later concatenation with `thursday_data`.
> Signals: Handle `KeyError` for no date for live_data 

- example_model.py
Divide by max for more accurate representation of drawdown risk
> fix drawdown code

- signals/quandl/README.md
- signals/quandl/example_model_quandl.py
Quandl example script for Signals and README in a new folder
> Signals: Quandl example script

- signals/example_model.py
renaming bloomberg_ticker to numerai_ticker as the default
> rename bloomberg_ticker to numerai_ticker

- signals/iexcloud/README.md
https://forum.numer.ai/t/new-data-source-iex-cloud-free-ish/3038
> added readme for iex cloud example script based on forum post

- signals/example_model.py
* changed ticker column name to `numerai_ticker` to avoid confusion in the last commit
* but the api hasn't changed, so just need to handle some renaming here to make the script run
> fix ticker header name

- signals/example_model.py
My bad, got the default filename wrong. Related to previous pull #70.
> got the filename wrong

- example_model.py
> Debugging help for XGBoost floating point error

- signals/example_model.py
This will also update example predictions to be generated from a model trained on 20D targets
> Update Signals example model to use 20d target

- example_model_advanced.py
*  need to scale all the preds before combining them, otherwise neutral and non-neutral models have very different weights than expected
* load model using the downsample suffix correctly, matching how we are saving them.
> scale all preds before ensemling

- example_model_advanced.py
- utils.py
Running the script example_model_advanced.py crashes on line 292 when trying to write the result to the directory prediction_files which isn't created beforehand.
> Fix crash when script tried to write to non existing directory

- utils.py
Add functionality for TB200 FNC, exposure dissimilarity
> Add functionality

- .gitignore
- README.md
- analysis_and_tips.ipynb
- hello_numerai.ipynb
- model_upload.ipynb
- rewrite readme 
- add hello numerai notebook
- add barebones model upload notebook
> rewrite readme, add hello numerai and model upload notebooks

- example_model.ipynb
- feature_neutralization.ipynb
- hello_numerai.ipynb
- target_ensemble.ipynb
Reverts numerai/example-scripts#148
> Revert "update pandas to 2.0.0"

- utils.py
update utils to mark everything as deprecated and make this as loud and explicit as possible
> Deprecate utils.py
